### ISSUE TITLE
啥时候支持GLM 系列的 tokenizer？

### ISSUE THREAD

**Issue by arvinxx** [lenML/llama2-tokenizer.js#1]
我想在 lobe-chat 中使用

**Comment by zhzLuke96** [comment]
这周应该就能搞完发包，下个版本就会支持

**Comment by jsxyhelu** [comment]
GLM4是支持了，如果我本地部署glm3-6b能够支持吗？

**Comment by zhzLuke96** [comment]
> GLM4是支持了，如果我本地部署glm3-6b能够支持吗？

GLM3已经支持，使用下面这个包即可
```@lenml/llama2-tokenizer-vocab-chatglm3```

ps: GLM4没开源吧？我这也没支持吧😂
pps: 这个issue结束了，其他问题请新开issue
