### ISSUE TITLE
Mistral vocab

### ISSUE THREAD

**Issue by DreamGenX** [lenML/llama2-tokenizer.js#3]
Great package! Thank you for bundling all these vocabs. Could you please also add Mistral?

**Comment by zhzLuke96** [comment]
Hello, thank you for your feedback. 

I'm glad to hear you like this library. In fact, the @lenml/llama2-tokenizer-vocab-llama2 package is already compatible with the Mistral vocabulary. So you just need to install and use this package to tokenize for Mistral.  

As you can see in the compatibility table:

```
| Library Name                           | Description                               | Compatibility                                        |
|---------------------------------------|-------------------------------------------|-------------------------------------------------------|  
| @lenml/llama2-tokenizer-vocab-llama2 | Vocabulary for llama2                    | mistral, zephyr, vicuna, llama2                       |
```

So no need to add a separate vocab package for Mistral. The existing vocab-llama2 package supports it out of the box.
